### ISSUE TITLE
CUDA memory errors in scrapeParticles

### ISSUE THREAD

**Issue by PhilMiller** [ECP-WarpX/WarpX#2534]
Running `development 13f6e984` under Nvidia's `compute-sanitizer`, and input from `Examples/Physics_applications/capacitive_discharge/inputs_2d`, I see the following errors reported:

> `compute-sanitizer ~/build/2021-11-05-GPU/bin/warpx inputs_2d`

```
========= Invalid __global__ read of size 4 bytes
=========     at 0x790 in /home/ubuntu/build/2021-11-05-GPU/_deps/fetchedamrex-src/Src/Base/AMReX_GpuLaunchFunctsG.H:899:_ZZN5amrex14ParallelForRNGIiZ15scrapeParticlesI22WarpXParticleContainerN23ParticleBoundaryProcess6AbsorbELi0EEvRT_RKNS_6VectorIPKNS_8MultiFabESaISA_EEEiiOT0_EUliRKNS_12RandomEngineEE_vEENSt9enable_ifIXsr5amrex19MaybeDeviceRunnableISF_vEE5valueEvE4typeES5_SG_ENKUlvE_clEv
=========     by thread (95,0,0) in block (17,0,0)
=========     Address 0x75cea828bfdc14fa is misaligned
=========     Device Frame:/home/ubuntu/build/2021-11-05-GPU/_deps/fetchedamrex-src/Src/Base/AMReX_GpuLaunchGlobal.H:16:_ZN5amrex13launch_globalILi256EZNS_14ParallelForRNGIiZ15scrapeParticlesI22WarpXParticleContainerN23ParticleBoundaryProcess6AbsorbELi0EEvRT_RKNS_6VectorIPKNS_8MultiFabESaISB_EEEiiOT0_EUliRKNS_12RandomEngineEE_vEENSt9enable_ifIXsr5amrex19MaybeDeviceRunnableISG_vEE5valueEvE4typeES6_SH_EUlvE_EEvSG_ [0xad0]
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x25428a]
=========                in /lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame: [0x78e0fb]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x7e1820]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x350e8d]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x3525c9]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x35380a]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x344b46]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x291a3d]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0xa8c94]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame:__libc_start_main [0x270b3]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame: [0xbfe2e]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
========= 
========= Invalid __global__ read of size 4 bytes
=========     at 0x790 in /home/ubuntu/build/2021-11-05-GPU/_deps/fetchedamrex-src/Src/Base/AMReX_GpuLaunchFunctsG.H:899:_ZZN5amrex14ParallelForRNGIiZ15scrapeParticlesI22WarpXParticleContainerN23ParticleBoundaryProcess6AbsorbELi0EEvRT_RKNS_6VectorIPKNS_8MultiFabESaISA_EEEiiOT0_EUliRKNS_12RandomEngineEE_vEENSt9enable_ifIXsr5amrex19MaybeDeviceRunnableISF_vEE5valueEvE4typeES5_SG_ENKUlvE_clEv
=========     by thread (32,0,0) in block (337,0,0)
=========     Address 0xb3dbc5afc001120c is out of bounds
=========     Device Frame:/home/ubuntu/build/2021-11-05-GPU/_deps/fetchedamrex-src/Src/Base/AMReX_GpuLaunchGlobal.H:16:_ZN5amrex13launch_globalILi256EZNS_14ParallelForRNGIiZ15scrapeParticlesI22WarpXParticleContainerN23ParticleBoundaryProcess6AbsorbELi0EEvRT_RKNS_6VectorIPKNS_8MultiFabESaISB_EEEiiOT0_EUliRKNS_12RandomEngineEE_vEENSt9enable_ifIXsr5amrex19MaybeDeviceRunnableISG_vEE5valueEvE4typeES6_SH_EUlvE_EEvSG_ [0xad0]
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x25428a]
=========                in /lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame: [0x78e0fb]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x7e1820]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x350e8d]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x3525c9]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x35380a]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x344b46]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0x291a3d]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame: [0xa8c94]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
=========     Host Frame:__libc_start_main [0x270b3]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame: [0xbfe2e]
=========                in /home/ubuntu/build/2021-11-05-GPU/bin/warpx
```

**Comment by PhilMiller** [comment]
`git bisect` points all the way back to https://github.com/ECP-WarpX/WarpX/pull/2069

**Comment by PhilMiller** [comment]
This is occurring in a problem with no actual embedded boundary

**Comment by ax3l** [comment]
attn @atmyers

**Comment by PhilMiller** [comment]
I've got a fix. There's one spot that doesn't respect the dimensionality of the build. It's not CUDA-specific

**Comment by PhilMiller** [comment]
It only comes up in a build with both EB and assertions enabled.

Can I recommend that the CI builds all have maximal assertions, even if they're otherwise optimized?

**Comment by PhilMiller** [comment]
On CPU with assertions, I got:

```
0::Assertion `i>=0 && i < SpaceDim' failed, file "_deps/fetchedamrex-src/Src/Base/AMReX_RealVect.H", line 97 !!!
```

With stack trace:

```
#12 0x000055555580b221 in amrex::Assert (msg=0x0, line=97, file=0x555555ba90e8 "_deps/fetchedamrex-src/Src/Base/AMReX_RealVect.H", EX=0x555555bbe068 "i>=0 && i < SpaceDim") at _deps/fetchedamrex-src/Src/Base/AMReX.H:175
#13 amrex::RealVect::operator[](int) & (i=2, this=<synthetic pointer>) at _deps/fetchedamrex-src/Src/Base/AMReX_RealVect.H:97
#14 scrapeParticles<WarpXParticleContainer, ParticleBoundaryProcess::Absorb, 0>(WarpXParticleContainer&, amrex::Vector<amrex::MultiFab const*, std::allocator<amrex::MultiFab const*> > const&, int, int, ParticleBoundaryProcess::Absorb&&)::{lambda(int, amrex::RandomEngine const&)#1}::operator()(int, amrex::RandomEngine const&) const (engine=..., ip=<optimized out>, this=0x7fffffffd200) at /home/ubuntu/repos/WarpX/Source/EmbeddedBoundary/ParticleScraper.H:176
#15 amrex::ParallelForRNG<int, scrapeParticles<WarpXParticleContainer, ParticleBoundaryProcess::Absorb, 0>(WarpXParticleContainer&, amrex::Vector<amrex::MultiFab const*, std::allocator<amrex::MultiFab const*> > const&, int, int, ParticleBoundaryProcess::Absorb&&)::{lambda(int, amrex::RandomEngine const&)#1}, void>(int, ParticleBoundaryProcess::Absorb&&) (f=..., n=<optimized out>) at _deps/fetchedamrex-src/Src/Base/AMReX_GpuLaunchFunctsC.H:541
#16 scrapeParticles<WarpXParticleContainer, ParticleBoundaryProcess::Absorb, 0> (pc=..., distance_to_eb=..., lev_min=lev_min@entry=0, lev_max=0, f=...) at /home/ubuntu/repos/WarpX/Source/EmbeddedBoundary/ParticleScraper.H:159
#17 0x00005555557db326 in scrapeParticles<WarpXParticleContainer, ParticleBoundaryProcess::Absorb, 0> (f=..., distance_to_eb=..., pc=...) at _deps/fetchedamrex-src/Src/Particle/AMReX_ParGDB.H:321
#18 MultiParticleContainer::ScrapeParticles (this=this@entry=0x555555d0e8f0, distance_to_eb=...) at /home/ubuntu/repos/WarpX/Source/Particles/MultiParticleContainer.cpp:1606
#19 0x000055555573a2c3 in WarpX::Evolve (this=0x7fffffffd9d0, numsteps=<optimized out>) at /usr/include/c++/9/bits/unique_ptr.h:360
#20 0x00005555555cece0 in main (argc=<optimized out>, argv=<optimized out>) at /home/ubuntu/repos/WarpX/Source/main.cpp:64
```

**Comment by ax3l** [comment]
Thanks a lot, great catch!

> Can I recommend that the CI builds all have maximal assertions, even if they're otherwise optimized?

Yes, we tried this - but especially bounds checks are so slow that we cannot run them on CI: #1883
