### ISSUE TITLE
Checksums & Analysis: Skip cpu & id

### ISSUE THREAD

**Issue by ax3l** [ECP-WarpX/WarpX#2865]
We want to run our regression tests in a way that we can validate the physics on CPUs and GPUs.

Thus, both the checksum API and the default analysis need to skip particle `cpu` and `id`.

- `Examples/analysis_default_restart.py`
- `Regression/Checksum/`

Currently, we see errors of the kind
```
  1 ./analysis_restart.py  restart_plt00010
  2 
  3 tolerance = 1e-12
  4 
  5 field: ('all', 'particle_cpu'); error = 0
  6 field: ('all', 'particle_id'); error = 0.0441377
  7 /gpfs/alpine/aph114/proj-shared/yin/2022_01_24_Crusher/warpx-ci-runs/py-venv/lib/python3.9/site-packages/yt/utilities/logger.py:4: VisibleDeprecationWarning: The configuration file /ccs/home/yinjianz/.config/yt/ytrc is deprecated in favor of /ccs/home/yinjianz/.config/yt/yt.toml. Currently, both are present    . Please manually remove the deprecated one to silence this warning.
  8 Deprecated since v4.0.0. This feature will be removed in v4.1.0
  9   from yt.config import ytcfg
 10 Traceback (most recent call last):
 11   File "/gpfs/alpine/aph114/proj-shared/yin/2022_01_24_Crusher/warpx-ci-runs/rt-WarpX/WarpX-tests/2022-02-16/restart/./analysis_restart.py", line 15, in <    module>
 12     check_restart(filename)
 13   File "../../../../warpx/Examples/analysis_default_restart.py", line 52, in check_restart
 14     assert(error < tolerance)
 15 AssertionError
```

when running on AMD GPUs, which is something we do not need to cover with regression tests.

These fields need to be excluded:
```
field: ('all', 'particle_cpu'); error = 0
field: ('all', 'particle_id'); error = 0.0441377
```
and probably the species-specific cpu/id as well.

**Comment by ax3l** [comment]
@MaxThevenet commented on Slack that:
> [...] most of the machinery should be there with `do_fields`  and `do_particles`

**Comment by ax3l** [comment]
@Yin-YinjianZhao we already do some filtering here:
https://github.com/ECP-WarpX/WarpX/blob/bc6991e6b58f455a139401c96d77dccfa35003a6/Regression/Checksum/checksum.py#L58-L60

and cpu/id filters would be similar :)
