### ISSUE TITLE
unable to run picviewer

### ISSUE THREAD

**Issue by bssharma58** [ECP-WarpX/WarpX#3331]
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
['Bx' 'By' 'Bz' 'Ex' 'Ey' 'Ez' 'jx' 'jy' 'jz' 'rho']
Traceback (most recent call last):
  File "/home/bhawani/anaconda3/bin/picviewer", line 33, in <module>
    sys.exit(load_entry_point('PICviewer==1.2.0', 'console_scripts', 'picviewer')())
  File "/home/bhawani/anaconda3/lib/python3.9/site-packages/PICviewer-1.2.0-py3.9.egg/picviewer/__main__.py", line 11, in launch_gui
    maincontrol = ControlCenter()
  File "/home/bhawani/anaconda3/lib/python3.9/site-packages/PICviewer-1.2.0-py3.9.egg/picviewer/controller/main_controller.py", line 78, in __init__
    self.initialization = Initialization(self.main, plotfile_prefix)
  File "/home/bhawani/anaconda3/lib/python3.9/site-packages/PICviewer-1.2.0-py3.9.egg/picviewer/controller/initialization.py", line 18, in __init__
    param_dic = self.datainfo.datainfo(self.main.filepath)
  File "/home/bhawani/anaconda3/lib/python3.9/site-packages/PICviewer-1.2.0-py3.9.egg/picviewer/dataloader/get_datainfo.py", line 59, in datainfo
    param_dic = getDatainfo(
  File "/home/bhawani/anaconda3/lib/python3.9/site-packages/PICviewer-1.2.0-py3.9.egg/picviewer/dataloader/get_warpxinfo.py", line 75, in WarpXinfo
    numpart = ds.particle_type_counts[species]
KeyError: 'nbody'
```

**Comment by ax3l** [comment]
Hi @bssharma58,

picviewer is a bit legacy/undermaintained from the tools we list in the docs. We will update accordingly.

opened an upstream bug report: https://bitbucket.org/ecp_warpx/picviewer/issues/2/yt-40-exclude-nbody

The fix for this is due to a change in yt 4.0 and would look similar to this patch, excluding `nbody`: https://github.com/ECP-WarpX/WarpX/pull/2060

**Comment by ax3l** [comment]
Thanks @dpgrote for taking a look on this :)

**Comment by ax3l** [comment]
Fixed via https://bitbucket.org/ecp_warpx/picviewer/pull-requests/10/various-fixes :)
