### ISSUE TITLE
Problem in running PICVIEWER 

### ISSUE THREAD

**Issue by bssharma1958** [ECP-WarpX/WarpX#3369]

**Comment by bssharma1958** [comment]
When I run any example with PICVIEWER, each time I am getting an error: key error : n particles . Could anyone  help me to get out of the error !

**Comment by ax3l** [comment]
Hi,

In order to get help from open source projects, you please need to post a reproducible error report.

Which version of PIC-viewer are you using?
What kind of operating system and which software environment (Python version, yt version, etc.), and which inputs file of WarpX are you using?
What is the complete error message & Python backtrace that you get?

**Comment by ax3l** [comment]
Updates seen on Gitter:
```
PICVIEWER fails to visualise the simulation results. Following is the error :
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
['Bx' 'By' 'Bz' 'Ex' 'Ey' 'Ez' 'jx' 'jy' 'jz' 'rho']
Traceback (most recent call last):
File "/home/bhawani/anaconda3/bin/picviewer", line 33, in <module>
sys.exit(load_entry_point('PICviewer==1.2.0', 'console_scripts', 'picviewer')())
File "/home/bhawani/anaconda3/lib/python3.9/site-packages/[PICviewer-1.2.0-py3.9.egg/picviewer/](http://picviewer-1.2.0-py3.9.egg/picviewer/)main.py", line 11, in launch_gui
maincontrol = ControlCenter()
File "/home/bhawani/anaconda3/lib/python3.9/site-packages/[PICviewer-1.2.0-py3.9.egg/picviewer/controller/main](http://picviewer-1.2.0-py3.9.egg/picviewer/controller/main)_controller.py", line 78, in init
self.initialization = Initialization(self.main, plotfile_prefix)
File "/home/bhawani/anaconda3/lib/python3.9/site-packages/[PICviewer-1.2.0-py3.9.egg/picviewer/controller/initialization.py](http://picviewer-1.2.0-py3.9.egg/picviewer/controller/initialization.py)", line 18, in init
param_dic = self.datainfo.datainfo(self.main.filepath)
File "/home/bhawani/anaconda3/lib/python3.9/site-packages/[PICviewer-1.2.0-py3.9.egg/picviewer/dataloader/get](http://picviewer-1.2.0-py3.9.egg/picviewer/dataloader/get)_datainfo.py", line 59, in datainfo
param_dic = getDatainfo(
File "/home/bhawani/anaconda3/lib/python3.9/site-packages/[PICviewer-1.2.0-py3.9.egg/picviewer/dataloader/get](http://picviewer-1.2.0-py3.9.egg/picviewer/dataloader/get)_warpxinfo.py", line 75, in WarpXinfo
numpart = ds.particle_type_counts[species]
KeyError: 'nbody'
Please help me out or suggest alternate method to visualise the results.
```

**Comment by ax3l** [comment]
@bssharma1958 your issue was recently fixed in PICviewer, see your duplicate issue in #3331 

Please update PICviewer (https://bitbucket.org/ecp_warpx/picviewer) and this will be gone.

**Comment by bssharma1958** [comment]
Bitbucket.org website not loading in my system. Machine loaded with OS
Ubuntu22.04

**Comment by ax3l** [comment]
Please uninstall and reinstall PICviewer the way you originally did, that should solve your problem.
